// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-k_0lAa7lNtSrx3w0a0YDbEqcRlf9f-w',
    appId: '1:653743462051:web:5de4f45480250e40729116',
    messagingSenderId: '653743462051',
    projectId: 'appnongsan-2791a',
    authDomain: 'appnongsan-2791a.firebaseapp.com',
    storageBucket: 'appnongsan-2791a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ruUT1-F80zPzHpWTId0nodN4Nmwhqto',
    appId: '1:653743462051:android:0ab8337280665474729116',
    messagingSenderId: '653743462051',
    projectId: 'appnongsan-2791a',
    storageBucket: 'appnongsan-2791a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-k_0lAa7lNtSrx3w0a0YDbEqcRlf9f-w',
    appId: '1:653743462051:web:1732bc14cf6587ab729116',
    messagingSenderId: '653743462051',
    projectId: 'appnongsan-2791a',
    authDomain: 'appnongsan-2791a.firebaseapp.com',
    storageBucket: 'appnongsan-2791a.appspot.com',
  );
}
